### ISSUE TITLE
What if I wanted to use wordpress 4.9.x ?

### ISSUE THREAD

**Issue by laymonk** [docksal/boilerplate-wordpress#4]
Hi,

I am quite impressed at how quickly Docksal bootsrapped a WordPress env for me, and I can login to wp-admin.  Well done for this awesome tool.

In the absence of any clear documentation, I am forced to ask what may be trivial questions:

* What if I wanted to use wordpress 4.9.x ?
* What is the recommended way to use wp-cli ?  
* How would I access the DB (if, not via wp-cli)?  ... eg: phpmyadmin, straigh mysqlclient login ? 

Just trying to save time by understanding the general intention of how Docksal should be used for WordPress. 

The better I understand it, the quicker I can contribute to docs, configs, boiler plates ... 

Thanks in advance for any suggestions, pointers ...

**Comment by laymonk** [comment]
OK ... I think I get it now.

* The wordpress (docroot) folder can be swapped out as required, for the preferred version, subject to a wp-config.php (and possible .htaccess) adaptation ... 
* wpcli is available as `fin wp <blah>` 
* Composer is available as `fin composer <blah>`

Not clear to me (yet) how to manage staging/production work flows, and the resultant change in config files between environments ... ie, using fin ... but I am working on it.  

Will close this ticket now.  Thank you.

**Comment by lmakarov** [comment]
> What if I wanted to use wordpress 4.9.x ?

There is no boilerplate repo with Wordpress 4 and also no docs for configuring an existing Wordpress project to use with Docksal, like there are for [Drupal](https://docs.docksal.io/tools/drupal/). I created an [issue](https://github.com/docksal/docksal/issues/1144) for that.

> How would I access the DB (if, not via wp-cli)?

See `fin db` commands

> Not clear to me (yet) how to manage staging/production work flows, and the resultant change in config files between environments

Docksal does not have an opinion about your dev workflow. It's entirely up to you how you'd want to manage it.
